export const INCREASE_NUMBER = 'INCREASE_NUMBER'
export const DECREASE_NUMBER = 'DECREASE_NUMBER'
export const GET_WEATHER_SUCCESS='GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAIL='GET_WEATHER_FAIL'